---
title: "data rep test"
author: "Julianna D."
date: "`r Sys.Date()`"
output: html_document
---
# Getting Started

## Load Packages
```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(segmented)
library(lubridate)
```

## Read Dataset
```{r}
regression_output <- read.csv("5._Regression_output.csv", stringsAsFactors = TRUE)
```

# Replicating Figure 3

## Separating the Data
```{r fig3, echo=FALSE, fig.height=6, fig.width=8, message=FALSE, warning=FALSE, paged.print=FALSE}

regression_output$Variable <- factor(regression_output$Variable, levels = c("hs",
                                                "healthins",
                                                "minority",
                                                "essential",
                                                "health",
                                                "essential_both",
                                                "median_age",
                                                "Median_Income",
                                                "subway_use"),
                       labels = c("High school education",
                                  "Uninsured",
                                  "Non-White/Hispanic",
                                  "Non-health-care essential services",
                                  "Health-care essential services",
                                  "All essential services",
                                  ">75 Years of age",
                                  "Median income",
                                  "Mobility")) #renaming the variables from the dataset for the legend

regression_output$Outcome <- factor(regression_output$Outcome, levels = c("COVID_adjusted","Subway_Use"),
                       labels = c("Rate of COVID-19 (per 100k)\n\nEstimate (adjusted for testing):\nRisk Ratio",
                                  "Mobility (10 Units)\n\nEstimate (unadjusted):\nbeta")) #separating the 'Outcome' column 

#SEPARATE TO MAKE 2 PANEL PLOT

df2 <- regression_output[1:8,]
df3 <- regression_output[9:17,]
df2$intercept <- 0 #the null is 0
df3$intercept <- 1 #the null for risk ratio is 1
```

## Mobility
```{r fig3, echo=FALSE, fig.height=6, fig.width=8, message=FALSE, warning=FALSE, paged.print=FALSE}
fig4_1 <- ggplot(data=df2, aes(x = Variable,y = RiskRatio, ymin = LowerLimit, ymax = UpperLimit )) +
  scale_y_continuous(limits=c(-.5,1.5), breaks = c(-.5,0,.5,1,1.5)) +
  geom_pointrange(cex=0.3) +
  geom_hline(data = df2, aes(fill=Variable, yintercept = intercept), linetype=2, show.legend = FALSE) + xlab('') + 
  ylab(expression(beta)) + geom_errorbar(aes(ymin=LowerLimit, ymax=UpperLimit), width=0.3,cex=0.7) +
  theme_classic(base_size=12) +
  coord_flip() + theme(legend.position="bottom") + guides(col=guide_legend(ncol=3, byrow=TRUE, reverse = TRUE, title.position = "bottom")) + theme(legend.text = element_text(size=12), text=element_text(size=12), axis.text=element_text(size=12, colour="black"), legend.margin = margin(10, 50, 10, 10)
)

plot(fig4_1)
```


## Risk Ratio
```{r fig3, echo=FALSE, fig.height=6, fig.width=8, message=FALSE, warning=FALSE, paged.print=FALSE}

fig4_2 <- ggplot(data=df3, aes(x = Variable,y = RiskRatio, ymin = LowerLimit, ymax = UpperLimit )) +
  scale_y_continuous(trans = "log", limits=c(.8,2.2), breaks = c(.8,1,1.2,1.4,1.6,1.8, 2.0, 2.2)) +
  geom_pointrange(cex=0.3) +
  geom_hline(data = df3, aes(fill=Variable, yintercept = intercept), linetype=2, show.legend = FALSE) + xlab('') + 
  ylab("Risk Ratio") + geom_errorbar(aes(ymin=LowerLimit, ymax=UpperLimit),width=0.3,cex=0.7) +
  theme_classic(base_size=12) +
  coord_flip() + theme(legend.position="bottom") + guides(col=guide_legend(ncol=3, byrow=TRUE, reverse = TRUE, title.position = "bottom")) + theme(legend.text = element_text(size=12), text=element_text(size=12), axis.text=element_text(size=12, colour="black"), legend.margin = margin(10, 50, 10, 10)
)

plot(fig4_2)
```

# Sources
