---
title: "regression output"
author: "Julianna D."
date: "`r Sys.Date()`"
output: html_document
---
```{r}
# Horizontal Example

# Load the plotrix package
library(plotrix)
 
# Create a data frame with some example data
df <- data.frame(
  group = c("A", "A", "B", "B", "C", "C"),
  value = c(10, 12, 8, 9, 6, 7)
)
 
# Calculate the means and standard errors for each group
means <- aggregate(value ~ group, data = df, FUN = mean)
stderrs <- aggregate(value ~ group, data = df, 
                     FUN = function(x) sd(x) / sqrt(length(x)))
 
# Create a dot chart of the data
dotchart(means$value, labels = means$group, xlim = c(0, max(means$value) * 1.1),
         xlab = "Value")
 
# Add error bars representing the standard error of the mean
arrows(
  x0 = means$value - stderrs$value,
  y0 = 1:length(means$group),
  x1 = means$value + stderrs$value,
  y1 = 1:length(means$group),
  angle = 90,
  code = 3,
  length = 0.1
)
```

```{r}
# Not correct but it's a start
library(ggplot2)
test <- ggplot(Regression_output, aes(Variable, Outcome, label=rownames(Regression_output))) +
  geom_point() +
  geom_errorbar(aes(ymin=LowerLimit, ymax=UpperLimit))
print(test)
```


```{r}
# Horizontal Error Bars
# Example from https://stackoverflow.com/questions/51344297/r-scatter-plot-with-confident-intervals

library(ggplot2)

df <- data.frame(method = LETTERS[1:3],
                 est = c(5.7, 6, 5.9),
                 lower = c(5.2, 5.5, 5.6),
                 upper = c(5.8, 6.4, 6.1))

ggplot(df, aes(x = est, y = method)) +
  geom_point() +
  geom_errorbarh(aes(xmin = lower, xmax = upper)) +
  geom_vline(aes(xintercept = 5.75), colour = "red") 
```


```{r}
library(ggplot2)
attach(Regression_output)
```

Trying one Outcome Variable at a time - Subway_Use
```{r}
attach(Book1)
library(ggplot2)
test20 <- ggplot(Book1, aes(Variable, Outcome,)) +
  geom_point() +
  geom_errorbar(aes(ymin=LowerLimit, ymax=UpperLimit))
print(test20)

```
```{r}
df <- data.frame(method = labels()[-0.5:2.5],
                 est = c(5.7, 6, 5.9),
                 lower = c(5.2, 5.5, 5.6),
                 upper = c(5.8, 6.4, 6.1))

ggplot(df, aes(x = est, y = method)) +
  geom_point() +
  geom_errorbarh(aes(xmin = lower, xmax = upper)) +
  geom_vline(aes(xintercept = 5.75), colour = "red") 


ggplot(df, aes(x = est, y = method)) +
  geom_point() +
  geom_errorbarh(aes(xmin = lower, xmax = upper)) +
  geom_vline(aes(xintercept = 5.75), colour = "red") 

ggplot(Book1, aes(x = Variable, y = Mean, fill = Group)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  geom_errorbar(aes(ymin = LowerCI, ymax = UpperCI), position = "dodge", width = 0.2) +
  labs(title = "Comparison of 95% Confidence Intervals between Groups",
       x = "Variable", y = "Mean") +
  theme_minimal()
```

